import os
import sys

from exception import TYException
from utils import (
    Clipboard,
    html2img,
    get_config,
    get_window_title,
    PrintWithoutHide,
)


def main(Config: dict):
    with Clipboard() as cb:
        html = cb.get_html()
        if html is None:
            return

        cb.write_img(
            html2img(html=html,
                     title=get_window_title(),
                     defualt_title=Config['TangYuan']['default_title'] or "Generated by TangYuan",
                     args=Config['TangYuan']['wk']),
            Config['TangYuan']['image_type'] or 'BMP'
        )


if __name__ == '__main__':
    sys.stdout = open(os.devnull, 'w')
    try:
        main(get_config())
    except Exception as e:
        TYException(e)
    else:
        with PrintWithoutHide():
            print("Success")
